# -*- coding: utf-8 -*-
"""Cat Dog image classifieripynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikNRsE9p8FzSYmM2133r3T_uO6I98Xvq

# **Cats vs Dogs Image Classification CNN**

The model consists of multiple layers, including convolutional layers, pooling layers, and fully connected layers. It predicts whether an image contains a cat or a dog using the Cats vs Dogs dataset.

1. The input layer takes images of size **128 × 128 × 3** and uses ReLU activation function.

2. The first convolution layer consists of 32 filters (3×3) followed by a MaxPooling layer to reduce the spatial dimensions.

3. The second convolution layer consists of 64 filters (3×3) followed by a MaxPooling layer for further feature extraction.

4. The third convolution layer consists of 128 filters (3×3) followed by a MaxPooling layer. A Dropout layer (0.3) is applied after this layer to reduce overfitting.

5. The fourth convolution layer consists of 128 filters (3×3) followed by a MaxPooling layer. A Dropout layer (0.3) is applied to further prevent overfitting and improve generalization.

6. The Flatten layer converts the 2D feature maps into a 1D vector for input into the dense layers.

7. Fully Connected Layers:

   * The first dense layer consists of 128 neurons and uses ReLU activation function followed by a Dropout layer (0.4).
   * The second dense layer consists of 64 neurons and uses ReLU activation function followed by a Dropout layer (0.35).
   * The third dense layer consists of 32 neurons and uses ReLU activation function followed by a Dropout layer (0.3).

8. The Output layer consists of 1 neuron and uses Sigmoid activation function and outputs a probability value between 0 and 1 (binary classification).

9. Model Structure: 128×128×3 (input) → 32 → Pool → 64 → Pool → 128 → Pool → Dropout → 128 → Pool → Dropout → Flatten → 128 → Dropout → 64 → Dropout → 32 → Dropout → 1 (output)

10. Training Configuration:

* Optimizer: Adam
* Loss Function: Binary Crossentropy
* Batch Size: 32
* Epochs: Up to 15 (with early stopping)

11. Regularization Techniques

* Dropout :- Applied in both convolutional and dense layers to randomly disable neurons during training, preventing the model from over-relying on specific features and reducing overfitting
* Early Stopping :- Monitors validation loss, stops training if no improvement for 3 epochs and restores best model weights, preventing overfitting

12. Evaluation Metrics

* Accuracy → overall correctness of predictions
* Loss → measures prediction error
* Validation Accuracy → performance on unseen validation data during training
* Test Accuracy → final performance of the model on test dataset
"""

!pip install tensorflow-datasets

import tensorflow as tf
from tensorflow.keras import layers, models
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import EarlyStopping

# Load dataset

dataset, info = tfds.load("cats_vs_dogs", with_info=True, as_supervised=True)


dataset = dataset["train"]

train_size = int(0.8 * len(dataset))
train_data = dataset.take(train_size)
test_data = dataset.skip(train_size)


def preprocess(image, label):
    image = tf.image.resize(image, (128, 128))
    image = image / 255.0
    return image, label

train_data = train_data.map(preprocess).batch(32)

test_data = test_data.map(preprocess).batch(32)

model = models.Sequential([

    # Convolution Layer 1
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(128,128,3)),
    layers.MaxPooling2D((2,2)),

    # Convolution Layer 2
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    # Convolution Layer 3
    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Dropout(0.3),

     # Convolution Layer 4
    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Dropout(0.3),

    # Flatten
    layers.Flatten(),
    # layers.GlobalAveragePooling2D(),

    # Fully Connected Layers

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.4),

    layers.Dense(64, activation='relu'),
    layers.Dropout(0.35),

    layers.Dense(32, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(1, activation='sigmoid')  # 2 classes (cat or dog)
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)


early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

history = model.fit(
    train_data,
    epochs=15,
    validation_data=(test_data),
    callbacks=[early_stop]
)

test_loss, test_acc = model.evaluate(test_data)
print("Test Accuracy:", test_acc)

predictions = model.predict(test_data)

for images, labels in test_data.take(1):
    preds = model.predict(images)
    print("Predicted:", tf.argmax(preds[0]).numpy())
    print("Actual:", labels[0].numpy())

