# -*- coding: utf-8 -*-
"""Celsius to Fahrenheit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWfBYvbhSUX4Ph4GxHbMmFVend_t0r88
"""

import tensorflow as tf
import pandas as pd
import numpy as np

data = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQYEI3pL1UqQFbHJtln2ltrD3CwjFYS-WTFerU2g7jJf_c4P1z9mGtv7xNorgB56qnbFpNbw9EAVMpo/pub?output=csv')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

X = data[['C']]
y = data['F']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Model
model = Sequential()
model.add(Dense(units=1, input_shape=(1,)))

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

model.compile(optimizer=optimizer, loss='mse', metrics=['mae'])

trained_model = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=40,
    verbose=1
)

# Evaluation
loss, mae = model.evaluate(X_test, y_test)
print("\nTest MAE:", mae)

celsius = 100


value = np.array([[celsius]])
value_scaled = scaler.transform(value)
prediction = model.predict(value_scaled)
print("Prediction : ", prediction[0])

actual_value = (9/5)*celsius + 32

print("Actual Value : ", actual_value)

