# -*- coding: utf-8 -*-
"""Deep Leaning Perceptron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IkqelJzB7-JV8Ft7pz2CwH0W0ftHeiMx
"""

import numpy as np

class Perceptron():
  weights = np.zeros(2)
  bias    = 0
  lr      = 0.1           # learning rate
  epochs  = 10

  def __init__(self, X, y, lr):
    self.X = X
    self.y = y
    self.lr = lr
    self.weights = np.zeros(self.X.shape[1])

  @staticmethod
  def step(z):
    return 1 if z >= 0 else 0

  def train(self, epochs):

    for epoch in range(epochs):
      errors = 0

      for xi, yi in zip(self.X, self.y):
        z = np.dot(self.weights, xi) + self.bias
        pred = Perceptron.step(z)
        err = yi - pred

        # print(f"Weights : {self.weights} Bias : {self.bias} Err : {err}")
        self.weights += self.lr * err * xi
        self.bias += self.lr * err
        errors = errors + 1 if err > 0 else errors

      print(f"Epoch {epoch+1}: errors={errors}, w={self.weights}, b={self.bias:.1f}")

      if(errors == 0):
        break

    print("\n--- Final Weights and Bias ---")
    print(f"Weights : {self.weights} and Bias : {self.bias:.2f}")

    print("\n--- Result ---")
    if(errors > 0):
      print(f"The model did not train successfully and has {errors} error(s).")
      return
    else:
      print(f"The model has trained successfully in {epoch+1} epochs and has 0 errors.")

    print("\n--- Predictions ---")
    for xi, yi in zip(self.X, self.y):
      pred = Perceptron.step(np.dot(self.weights, xi) + self.bias)
      print(f"Input {xi} → pred={pred}, actual={yi}")

# AND gate

X1 = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y1 = np.array([0, 0, 0, 1])   # AND labels

P1 = Perceptron(X1, y1, 0.1)
P1.train(10)

# OR gate

X2 = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y2 = np.array([0, 1, 1, 1])   # OR labels

P2 = Perceptron(X2, y2, 0.1)
P2.train(10)

# NOT gate

X3 = np.array([[0], [1]])
y3 = np.array([1, 0])   # NOT labels

P3 = Perceptron(X3, y3, 0.1)
P3.train(10)

# XOR gate

X4 = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y4 = np.array([1, 0, 0, 1])   # XOR labels

P4 = Perceptron(X4, y4, 0.1)
P4.train(10)

