# -*- coding: utf-8 -*-
"""Exp-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vLNRRJUyvx48sdwzIXG1lzqr8V3CYGOz

# **Breast Cancer Classification ANN with Cross Validation and Model Selection**

The model consists of fully connected layers and uses a systematic approach with cross validation to determine the optimal architecture. It predicts whether a tumor is malignant or benign using the Breast Cancer dataset.

1. The input layer takes **30 numerical features** and feeds them into the network using ReLU activation function.

2. The first dense layer consists of a variable number of neurons (tested across 4, 8, 16, 32, and 64) and uses ReLU activation function to capture initial feature relationships.

3. A Dropout layer (0.05) is applied after the first layer to randomly disable neurons during training, reducing overfitting and improving generalization.

4. The second dense layer consists of the same number of neurons as the first layer and uses Tanh activation function for non-linear transformation of features.

5. The Output layer consists of 1 neuron and uses Sigmoid activation function to produce a probability value between 0 and 1 for binary classification.

6. Model Structure: 30 (input) → N → Dropout → N → 1 (output), where N ∈ {4, 8, 16, 32, 64}

7. Cross Validation and Model Selection:

   * Stratified K-Fold (k=3) is used to split the training data into multiple folds while maintaining class balance.
   * For each neuron configuration, the model is trained 3 times on different splits.
   * Mean Accuracy and Mean Loss are computed across folds to evaluate performance.
   * The model with the highest mean validation accuracy is selected as the best configuration.

8. Training Configuration:

   * Optimizer: Adam
   * Loss Function: Binary Crossentropy
   * Batch Size: 16
   * Epochs: Up to 50 (with early stopping)

9. Regularization Techniques:

   * Dropout :- Randomly disables neurons during training to prevent overfitting and improve generalization
   * Early Stopping :- Monitors validation loss, stops training if no improvement for 10 epochs and restores best model weights
   * Model Checkpoint :- Saves the best-performing model during training based on validation loss

10. Evaluation Metrics:

* Accuracy → overall correctness of predictions
* Loss → measures prediction error
* R² Score → indicates how well predictions align with actual values
* Confusion Matrix → shows correct and incorrect classifications
* Precision, Recall, F1-score → evaluate classification performance for each class

11. Final Outcome:

* The optimal model was obtained with **8 neurons**, achieving the highest mean validation accuracy during cross validation.
* The final trained model demonstrated high accuracy and strong generalization on unseen test data with minimal misclassification.
"""

# **Breast Cancer Classification ANN (Improved Search + Clean Output)**

!pip install -U scikeras scikit-learn -q

import warnings, os
warnings.filterwarnings("ignore")
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, r2_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# -----------------------------
# 1. Load Dataset
# -----------------------------
data = load_breast_cancer()
X = data.data
y = data.target

# -----------------------------
# 2. Train-Test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -----------------------------
# 3. Feature Scaling
# -----------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# -----------------------------
# 4. Model Function
# -----------------------------
def build_model(neurons=16):
    model = Sequential([
        Input(shape=(30,)),
        Dense(neurons, activation='relu'),
        Dropout(0.05),
        Dense(neurons, activation='tanh'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

# -----------------------------
# 5. Manual Grid Search + CV (clean output)
# -----------------------------
neurons_list = [4, 8, 16, 32, 64]
kf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

results = []
best_score = 0
best_neurons = None

for n in neurons_list:
    fold_acc = []
    fold_loss = []

    for train_idx, val_idx in kf.split(X_train, y_train):
        X_tr, X_val = X_train[train_idx], X_train[val_idx]
        y_tr, y_val = y_train[train_idx], y_train[val_idx]

        model = build_model(n)

        model.fit(
            X_tr, y_tr,
            validation_data=(X_val, y_val),
            epochs=30,
            batch_size=16,
            verbose=0
        )

        loss, acc = model.evaluate(X_val, y_val, verbose=0)
        fold_acc.append(acc)
        fold_loss.append(loss)

    mean_acc = np.mean(fold_acc)
    mean_loss = np.mean(fold_loss)

    print(f"Neurons: {n} → Mean Accuracy: {mean_acc:.4f}, Mean Loss: {mean_loss:.4f}")

    if mean_acc > best_score:
        best_score = mean_acc
        best_neurons = n

print(f"\nBest Neurons: {best_neurons}")

# -----------------------------
# 6. Final Model
# -----------------------------
model = build_model(best_neurons)

early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
checkpoint = ModelCheckpoint("best_model.keras", monitor="val_loss", save_best_only=True)

model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=50,
    batch_size=16,
    callbacks=[early_stop, checkpoint],
    verbose=0
)

# -----------------------------
# 7. Evaluation
# -----------------------------
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)

y_pred_prob = model.predict(X_test, verbose=0)
y_pred = (y_pred_prob > 0.5).astype(int)

r2 = r2_score(y_test, y_pred)

print("\nFinal Model Performance:")
print("Test Accuracy:", accuracy)
print("R2 Score:", r2)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

