# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LPgbPFgfnQF2Csx7XR946lubjXW3y7sm

# **CIFAR-10 Image Classification using Transfer Learning (VGG16)**

The model uses a pre-trained convolutional neural network **VGG16** for feature extraction and adds custom fully connected layers for classification. It predicts the class of objects present in images using the CIFAR-10 dataset.

1. The input layer takes images of size **96 × 96 × 3** and uses ReLU activation function after preprocessing and normalization.

2. The pre-trained VGG16 model (without the top layers) is used as the base model to extract high-level features from input images.

3. All layers of the VGG16 model are frozen to retain the pre-trained weights and prevent them from being updated during training.

4. The Flatten layer converts the extracted 2D feature maps into a 1D vector for input into the dense layers.

5. Fully Connected Layers:

   * The first dense layer consists of 256 neurons and uses ReLU activation function followed by a Dropout layer (0.4).
   * The second dense layer consists of 128 neurons and uses ReLU activation function followed by a Dropout layer (0.2).

6. The Output layer consists of 10 neurons and uses Softmax activation function to classify the input image into one of the 10 classes.

7. Model Structure: 96×96×3 (input) → VGG16 (feature extractor) → Flatten → 256 → Dropout → 128 → Dropout → 10 (output)

8. Training Configuration:

* Optimizer: Adam
* Loss Function: Sparse Categorical Crossentropy
* Batch Size: 32
* Epochs: Up to 30 (with early stopping)

9. Regularization Techniques

* Dropout :- Applied in dense layers to randomly disable neurons during training, preventing overfitting and improving generalization
* Early Stopping :- Monitors validation loss, stops training if no improvement for 3 epochs and restores best model weights, preventing overfitting

10. Evaluation Metrics

* Accuracy → overall correctness of predictions
* Loss → measures prediction error
* Validation Accuracy → performance on unseen validation data during training
* Test Accuracy → final performance of the model on test dataset

11. Transfer Learning Concept

* The pre-trained VGG16 model acts as a fixed feature extractor, capturing general image features such as edges, textures, and shapes
* Custom dense layers are trained on top of these features to adapt the model to the CIFAR-10 dataset
* This approach reduces training time and improves performance compared to training a model from scratch
"""

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import VGG16
from tensorflow.keras.callbacks import EarlyStopping

pip install datasets

from datasets import load_dataset

# Load CIFAR-10 dataset from Hugging Face
dataset = load_dataset('cifar10')

# Convert to numpy arrays expected by Keras
x_train_hf = []
y_train_hf = []
for item in dataset['train']:
    x_train_hf.append(item['img'])
    y_train_hf.append(item['label'])

x_test_hf = []
y_test_hf = []
for item in dataset['test']:
    x_test_hf.append(item['img'])
    y_test_hf.append(item['label'])

import numpy as np
x_train = np.array(x_train_hf)
y_train = np.array(y_train_hf)
x_test = np.array(x_test_hf)
y_test = np.array(y_test_hf)

print(f"Shape of x_train: {x_train.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of x_test: {x_test.shape}")
print(f"Shape of y_test: {y_test.shape}")

train_data = tf.data.Dataset.from_tensor_slices((x_train, y_train))
test_data = tf.data.Dataset.from_tensor_slices((x_test, y_test))

def preprocess(image, label):
    image = tf.image.resize(image, (96,96))
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

train_data = train_data.shuffle(10000).map(preprocess).batch(64)
test_data = test_data.map(preprocess).batch(128)

base_model = VGG16(
    weights='imagenet',
    include_top=False,
    input_shape=(96,96,3)
)

for layer in base_model.layers:
    layer.trainable = False

for layer in base_model.layers[-4:]:
    layer.trainable = True

model = models.Sequential([
    base_model,

    layers.Flatten(),

    layers.Dense(256, activation='relu'),
    layers.Dropout(0.35),

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.2),

    layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

history = model.fit(
    train_data,
    epochs=30,
    validation_data=test_data,
    callbacks=[early_stop]
)

test_loss, test_acc = model.evaluate(test_data)
print("Test Accuracy:", test_acc)

